### ISSUE TITLE
Migration to ReadTheDocs.org

### ISSUE THREAD

**Issue by marmotz** [atoum/atoum-documentation#43]
Migration in progress.

You can see the result on http://atoum.readthedocs.org
# TODO
- [x] translate from skriv to reST
- [x] configure ReadTheDocs for automatic html build for fr and en
- [x] fix the pdf build (it doesn't work for now)
- [ ] ~~create a custom html template~~ (maybe later)
- [x] configure ReadTheDocs to be accessible by docs.atoum.org
